name: android_build

on:
  push:
    branches:
      - main
      - test


jobs:
release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
      - name: Install Fastlane
        run: cd android && bundle install && cd ..
      - name: Install packages
        run: flutter pub get
      - name: Prebuild
        run: flutter build appbundle
      - name: Execute Fastlane command
        run: cd android && fastlane release


#      - run: flutter build apk
#      - name: Push to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/flutter-apk/*"
#          tag: android.v2.0.1.${{github.run_number}}
#          allowUpdates: true
#          generateReleaseNotes: true
#          makeLatest: true
#          token: ${{secrets.RELEASES_ACCESS_TOKEN}}
#      - name: Upload artifacts to firebase app distribution
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: ${{secrets.FIREBASE_APP_ID}}
#          token: ${{secrets.FIREBASE_TOKEN}}
##          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
#          groups: android_testers
#          file: "build/app/outputs/flutter-apk/app-release.apk"
#      - name: Install Fastlane
#        uses: fastlane/fastlane@2.4.1
#        with:
#          version: '2.190.0'
#
#      - name: Fastlane Bundle Install
#        run: bundle install
#        working-directory: android
#
#      - name: Fastlane Build APK
#        run: bundle exec fastlane build_apk
#        working-directory: android
#
#      - name: Release to Play Store
#        run: bundle exec fastlane release_to_playstore
#        working-directory: android
#
#
#
#
