name: build_test_search_and_book

on:
  push:
    branches:
      - main
      - test


jobs:
  build_test_notify:
    name: test_build_release_notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test


