name: build_test_search_and_book

on:
  push:
    branches:
      - main
      - test


jobs:
  build_test_notify:
    name: build_test_notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.TOKEN}}
      - name: Upload artifacts to firebase app distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_APP_TOKEN}}
          groups: android
          file: "build/app/outputs/flutter-apk/app-release.apk"


