name: ios_build

on:
  push:
    branches:
      - main
      - test


jobs:
  build_test_notify:
    name: ios_build_release_distribute
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: | 
           cd ios
           pod deintegrate
           pod repo update
           pod install
      - run: | 
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ..Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/ios/iphoneos/app.ipa*"
          tag: ios.v1.0.${{github.run_number}}
          allowUpdates: true
          token: ${{secrets.TOKEN}}
      - name: Upload artifacts to firebase app distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
#          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: ios_testers
          file: "build/ios/iphoneos/app.ipa"


